name: 'Add a new comment to a specific issue'
description: 'This action updates a specific issue with a new, templated comment, on a schedule.'
author: '@skullface'
branding:
  icon: 'calendar'
  color: 'yellow'

on:
  schedule:
    # Define your own schedule after "cron: "
    # Add a comment to the end of the line to read it in plain language 🕓
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    - cron: 30 17 * * FRI # Every Friday at 17:30 UTC (5:30pm UTC / 9:30am PT)

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: 420, # replace with the number of the specific issue the action will comment on
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `# Replace me with your own content!
              
              Use multiple lines of **Markdown** here to create your own templated issue comment.
              
              | Even | Tables | 
              | --- | --- |
              | If you | want to |
              
              Just keep the comment body between the backticks.
              `
            })
